### ISSUE TITLE
[question] hosting

### ISSUE THREAD

**Issue by francoisromain** [6stringbeliever/nuxt_wp#1]
Thank you for the interesting article. 
how do you handle hosting on a single domain on a shared hosting. 
can wordpress be in a subdirectory?

**Comment by 6stringbeliever** [comment]
Hi François,
Thanks for reading. 👍

So, first of all, your WordPress instance is really just an API server in this setup, so it doesn't really matter to Nuxt where it lives as long as it's accessible. So, if you stick your WordPress instance in a directory, your API endpoint now just becomes example.com/wpdir/api.

That said, Nuxt is a node application, so you're probably not going to be able to run it in server-side rendering (SSR) mode in production on the same shared hosting as you're running WordPress on.

You can, however, use Nuxt in either static-generated or SPA mode. In these cases, you would use Nuxt to build your application locally and then deploy the generated content to your domain. So, you wanted your site to be at the root, you would deploy the generated content to your public_html (or whatever) folder. In that case, yes, you're right that you would probably want to put your WordPress instance in a subdirectory. This may also require some tweaking of your `.htaccess` files to make sure requests to WordPress don't get intercepted by your Nuxt app. YMMV on that one.

Nuxt doc has a lot more info on your deployment options: https://nuxtjs.org/guide/commands#production-deployment

And my next post in the series will be focusing on deploying.

Thanks again. Hope that helps.

**Comment by francoisromain** [comment]
Hello Shaun and thank you for your detailed answer. 

For the current project, the client already has an apache shared hosting and wants to use wp as a backend. So I was thinking to use nuxtjs in `spa` mode so it can run on an apache server (with no ssr). But urls were conflicting. In the end, I am trying to build a wordpress theme with a single index.php file loading the vuejs spa querying the wordpress rest api.

**Comment by marcosleonel** [comment]
Thank you for the article.
I follow the steps and I am getting the following error:
`Vue warn]: Property or method "posts" is not defined on the instance but referenced during render. Make sure that this property is reac
tive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity
.html#Declaring-Reactive-Properties.

found in

---> <Pages/index.vue> at pages/index.vue
       <Nuxt>
         <Default> at layouts/default.vue
           <Root>`

May you help me with that?

**Comment by bovas85** [comment]
This wouldn't work on a nuxt generate static site. Any idea on how to fix that?

**Comment by 6stringbeliever** [comment]
I plan on writing more about that in the next post, but you can read more about how to do static generation with dynamic routes in the next doc here:  https://nuxtjs.org/api/configuration-generate#routes

**Comment by bovas85** [comment]
Yes I'm aware, but having nuxtServerInit with this approach will likely spam the wordpress database with too many queries.
It will be run on each route, and if you have 10+ posts, this will likely bring the database down.

**Comment by 6stringbeliever** [comment]
That issue is covered in the doc.

**Comment by bovas85** [comment]
Not really. The doc covers using a payload nut that doesn't solve the issue.
